package servico;

/**
 * _ServicoEventosStub.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from ServicoEventos.idl
 * Terça-feira, 28 de Abril de 2009 20h14min44s BRT
 */
public class _ServicoEventosStub extends org.omg.CORBA.portable.ObjectImpl implements ServicoEventos {

    public boolean MeRegistre(org.omg.CORBA.Object ref, String evento) {
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            org.omg.CORBA.portable.OutputStream $out = _request("MeRegistre", true);
            org.omg.CORBA.ObjectHelper.write($out, ref);
            $out.write_string(evento);
            $in = _invoke($out);
            boolean $result = $in.read_boolean();
            return $result;
        } catch (org.omg.CORBA.portable.ApplicationException $ex) {
            $in = $ex.getInputStream();
            String _id = $ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException $rm) {
            return MeRegistre(ref, evento);
        } finally {
            _releaseReply($in);
        }
    } // MeRegistre

    public void ObterListaEventos(listaEventosHolder lista) {
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            org.omg.CORBA.portable.OutputStream $out = _request("ObterListaEventos", true);
            $in = _invoke($out);
            lista.value = ServicoEventosPackage.listaEventosHelper.read($in);
            return;
        } catch (org.omg.CORBA.portable.ApplicationException $ex) {
            $in = $ex.getInputStream();
            String _id = $ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException $rm) {
            ObterListaEventos(lista);
        } finally {
            _releaseReply($in);
        }
    } // ObterListaEventos

    public boolean NovoEvento(String evento) {
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            org.omg.CORBA.portable.OutputStream $out = _request("NovoEvento", true);
            $out.write_string(evento);
            $in = _invoke($out);
            boolean $result = $in.read_boolean();
            return $result;
        } catch (org.omg.CORBA.portable.ApplicationException $ex) {
            $in = $ex.getInputStream();
            String _id = $ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException $rm) {
            return NovoEvento(evento);
        } finally {
            _releaseReply($in);
        }
    } // NovoEvento

    public boolean CadastrarEvento(String evento) {
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            org.omg.CORBA.portable.OutputStream $out = _request("CadastrarEvento", true);
            $out.write_string(evento);
            $in = _invoke($out);
            boolean $result = $in.read_boolean();
            return $result;
        } catch (org.omg.CORBA.portable.ApplicationException $ex) {
            $in = $ex.getInputStream();
            String _id = $ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException $rm) {
            return CadastrarEvento(evento);
        } finally {
            _releaseReply($in);
        }
    } // CadastrarEvento

    public boolean obterEventoQualquer(org.omg.CORBA.StringHolder evento) {
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            org.omg.CORBA.portable.OutputStream $out = _request("obterEventoQualquer", true);
            $in = _invoke($out);
            boolean $result = $in.read_boolean();
            evento.value = $in.read_string();
            return $result;
        } catch (org.omg.CORBA.portable.ApplicationException $ex) {
            $in = $ex.getInputStream();
            String _id = $ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException $rm) {
            return obterEventoQualquer(evento);
        } finally {
            _releaseReply($in);
        }
    } // obterEventoQualquer

    public boolean checkpoint(byte[] estado) {
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            org.omg.CORBA.portable.OutputStream $out = _request("checkpoint", true);
            ServicoEventosPackage.arrayDeBytesHelper.write($out, estado);
            $in = _invoke($out);
            boolean $result = $in.read_boolean();
            return $result;
        } catch (org.omg.CORBA.portable.ApplicationException $ex) {
            $in = $ex.getInputStream();
            String _id = $ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException $rm) {
            return checkpoint(estado);
        } finally {
            _releaseReply($in);
        }
    } // checkpoint

    public boolean log(String copiaRequisicao, String evento, org.omg.CORBA.Object ref) {
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            org.omg.CORBA.portable.OutputStream $out = _request("log", true);
            $out.write_string(copiaRequisicao);
            $out.write_string(evento);
            org.omg.CORBA.ObjectHelper.write($out, ref);
            $in = _invoke($out);
            boolean $result = $in.read_boolean();
            return $result;
        } catch (org.omg.CORBA.portable.ApplicationException $ex) {
            $in = $ex.getInputStream();
            String _id = $ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException $rm) {
            return log(copiaRequisicao, evento, ref);
        } finally {
            _releaseReply($in);
        }
    } // log
    // Type-specific CORBA::Object operations
    private static String[] __ids = {
        "IDL:ServicoEventos:1.0"};

    public String[] _ids() {
        return (String[]) __ids.clone();
    }

    private void readObject(java.io.ObjectInputStream s) throws java.io.IOException {
        String str = s.readUTF();
        String[] args = null;
        java.util.Properties props = null;
        org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init(args, props).string_to_object(str);
        org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate();
        _set_delegate(delegate);
    }

    private void writeObject(java.io.ObjectOutputStream s) throws java.io.IOException {
        String[] args = null;
        java.util.Properties props = null;
        String str = org.omg.CORBA.ORB.init(args, props).object_to_string(this);
        s.writeUTF(str);
    }
} // class _ServicoEventosStub
