package servico;


/**
* ServicoEventosPackage/arrayDeBytesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServicoEventos.idl
* Ter�a-feira, 28 de Abril de 2009 20h14min44s BRT
*/

public final class arrayDeBytesHolder implements org.omg.CORBA.portable.Streamable
{
  public byte value[] = null;

  public arrayDeBytesHolder ()
  {
  }

  public arrayDeBytesHolder (byte[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = servico.arrayDeBytesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    servico.arrayDeBytesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return servico.arrayDeBytesHelper.type ();
  }

}
