package servico;

/**
 * ServicoEventos.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from ServicoEventos.idl
 * Quinta-feira, 30 de Abril de 2009 20h02min23s BRT
 */
public interface ServicoEventos extends ServicoEventosOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity {
} // interface ServicoEventos
