package servico;


/**
* ServicoEventosOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServicoEventos.idl
* Ter�a-feira, 31 de Mar�o de 2009 19h59min33s BRT
*/

public interface ServicoEventosOperations 
{
  boolean MeRegistre (org.omg.CORBA.Object ref, String evento);
  void ObterListaEventos (servico.listaEventosHolder lista);
  boolean NovoEvento (String evento);
  boolean CadastrarEvento (String evento);
  boolean obterEventoQualquer (org.omg.CORBA.StringHolder evento);
} // interface ServicoEventosOperations
