package detector;

/**
 * DetectorEventosHolder.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from DetectorEventos.idl
 * Quinta-feira, 30 de Abril de 2009 19h48min29s BRT
 */
public final class DetectorEventosHolder implements org.omg.CORBA.portable.Streamable {

    public DetectorEventos value = null;

    public DetectorEventosHolder() {
    }

    public DetectorEventosHolder(DetectorEventos initialValue) {
        value = initialValue;
    }

    public void _read(org.omg.CORBA.portable.InputStream i) {
        value = DetectorEventosHelper.read(i);
    }

    public void _write(org.omg.CORBA.portable.OutputStream o) {
        DetectorEventosHelper.write(o, value);
    }

    public org.omg.CORBA.TypeCode _type() {
        return DetectorEventosHelper.type();
    }
}
