package detector;

/**
 * DetectorEventosOperations.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from DetectorEventos.idl
 * Quinta-feira, 30 de Abril de 2009 19h48min29s BRT
 */
public interface DetectorEventosOperations {

    boolean TrocaServidor(org.omg.CORBA.Object ref);
} // interface DetectorEventosOperations
