package detector;

/**
 * DetectorEventos.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from DetectorEventos.idl
 * Quinta-feira, 30 de Abril de 2009 19h48min29s BRT
 */
public interface DetectorEventos extends DetectorEventosOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity {
} // interface DetectorEventos
