package detector;

/**
 * DetectorEventosPOA.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from DetectorEventos.idl
 * Quinta-feira, 30 de Abril de 2009 19h48min29s BRT
 */
public abstract class DetectorEventosPOA extends org.omg.PortableServer.Servant
        implements DetectorEventosOperations, org.omg.CORBA.portable.InvokeHandler {

    // Constructors
    private static java.util.Hashtable _methods = new java.util.Hashtable();

    static {
        _methods.put("TrocaServidor", new java.lang.Integer(0));
    }

    public org.omg.CORBA.portable.OutputStream _invoke(String $method,
            org.omg.CORBA.portable.InputStream in,
            org.omg.CORBA.portable.ResponseHandler $rh) {
        org.omg.CORBA.portable.OutputStream out = null;
        java.lang.Integer __method = (java.lang.Integer) _methods.get($method);
        if (__method == null) {
            throw new org.omg.CORBA.BAD_OPERATION(0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
        }

        switch (__method.intValue()) {
            case 0: // DetectorEventos/TrocaServidor
            {
                org.omg.CORBA.Object ref = org.omg.CORBA.ObjectHelper.read(in);
                boolean $result = false;
                $result = this.TrocaServidor(ref);
                out = $rh.createReply();
                out.write_boolean($result);
                break;
            }

            default:
                throw new org.omg.CORBA.BAD_OPERATION(0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
        }

        return out;
    } // _invoke
    // Type-specific CORBA::Object operations
    private static String[] __ids = {
        "IDL:DetectorEventos:1.0"};

    public String[] _all_interfaces(org.omg.PortableServer.POA poa, byte[] objectId) {
        return (String[]) __ids.clone();
    }

    public DetectorEventos _this() {
        return DetectorEventosHelper.narrow(
                super._this_object());
    }

    public DetectorEventos _this(org.omg.CORBA.ORB orb) {
        return DetectorEventosHelper.narrow(
                super._this_object(orb));
    }
} // class DetectorEventosPOA
