package cliente;


import cliente.ClienteEventos;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.Properties;
import org.omg.CORBA.MARSHAL;
import org.omg.CORBA.ORB;
import org.omg.CORBA.Object;
import org.omg.CORBA.portable.ApplicationException;
import org.omg.CORBA.portable.Delegate;
import org.omg.CORBA.portable.InputStream;
import org.omg.CORBA.portable.ObjectImpl;
import org.omg.CORBA.portable.OutputStream;
import org.omg.CORBA.portable.RemarshalException;


/**
 * _ClienteEventosStub.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from ClienteEventos.idl
 * Terça-feira, 31 de Março de 2009 20h11min01s BRT
 */
public class _ClienteEventosStub extends ObjectImpl implements ClienteEventos {

    public boolean NovoAlerta(String evento) {
        InputStream $in = null;
        try {
            OutputStream $out = _request("NovoAlerta", true);
            $out.write_string(evento);
            $in = _invoke($out);
            boolean $result = $in.read_boolean();
            return $result;
        } catch (ApplicationException $ex) {
            $in = $ex.getInputStream();
            String _id = $ex.getId();
            throw new MARSHAL(_id);
        } catch (RemarshalException $rm) {
            return NovoAlerta(evento);
        } finally {
            _releaseReply($in);
        }
    } // NovoAlerta
    // Type-specific CORBA::Object operations
    private static String[] __ids = {
        "IDL:ClienteEventos:1.0"};

    public String[] _ids() {
        return (String[]) __ids.clone();
    }

    private void readObject(ObjectInputStream s) throws IOException {
        String str = s.readUTF();
        String[] args = null;
        Properties props = null;
        Object obj = ORB.init(args, props).string_to_object(str);
        Delegate delegate = ((ObjectImpl) obj)._get_delegate();
        _set_delegate(delegate);
    }

    private void writeObject(ObjectOutputStream s) throws IOException {
        String[] args = null;
        Properties props = null;
        String str = ORB.init(args, props).object_to_string(this);
        s.writeUTF(str);
    }
} // class _ClienteEventosStub
