package cliente;


/**
* ClienteEventos.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClienteEventos.idl
* Ter�a-feira, 31 de Mar�o de 2009 20h11min01s BRT
*/

public interface ClienteEventos extends ClienteEventosOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ClienteEventos
