package cliente;

/**
 * ClienteEventos.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from ClienteEventos.idl
 * Quinta-feira, 30 de Abril de 2009 19h08min13s BRT
 */
public interface ClienteEventos extends ClienteEventosOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity {
} // interface ClienteEventos
