package cliente;

/**
 * ClienteEventosOperations.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from ClienteEventos.idl
 * Terça-feira, 31 de Março de 2009 20h11min01s BRT
 */
public interface ClienteEventosOperations {

    boolean NovoAlerta(String evento);
} // interface ClienteEventosOperations
