package cliente;

/**
* ClienteEventosOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClienteEventos.idl
* Quinta-feira, 30 de Abril de 2009 19h08min13s BRT
*/

public interface ClienteEventosOperations 
{
  boolean NovoAlerta (String evento);
  boolean TrocaServidor (org.omg.CORBA.Object ref);
} // interface ClienteEventosOperations
