package banco;


/**
* banco/aplicacaoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banco.idl
* Quarta-feira, 25 de Março de 2009 21h10min03s BRT
*/

abstract public class aplicacaoHelper
{
  private static String  _id = "IDL:banco/aplicacao:1.0";

  public static void insert (org.omg.CORBA.Any a, banco.aplicacao that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static banco.aplicacao extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (banco.aplicacaoHelper.id (), "aplicacao", new String[] { "poupanca", "fundo_acoes", "renda_fixa"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static banco.aplicacao read (org.omg.CORBA.portable.InputStream istream)
  {
    return banco.aplicacao.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, banco.aplicacao value)
  {
    ostream.write_long (value.value ());
  }

}
