package banco;


/**
* banco/aplicacao.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banco.idl
* Quarta-feira, 25 de Março de 2009 21h10min03s BRT
*/

public class aplicacao implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static banco.aplicacao[] __array = new banco.aplicacao [__size];

  public static final int _poupanca = 0;
  public static final banco.aplicacao poupanca = new banco.aplicacao(_poupanca);
  public static final int _fundo_acoes = 1;
  public static final banco.aplicacao fundo_acoes = new banco.aplicacao(_fundo_acoes);
  public static final int _renda_fixa = 2;
  public static final banco.aplicacao renda_fixa = new banco.aplicacao(_renda_fixa);

  public int value ()
  {
    return __value;
  }

  public static banco.aplicacao from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected aplicacao (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class aplicacao
