package banco;

/**
* banco/auto_atendimentoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banco.idl
* Quarta-feira, 25 de Março de 2009 21h10min03s BRT
*/

public final class auto_atendimentoHolder implements org.omg.CORBA.portable.Streamable
{
  public banco.auto_atendimento value = null;

  public auto_atendimentoHolder ()
  {
  }

  public auto_atendimentoHolder (banco.auto_atendimento initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = banco.auto_atendimentoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    banco.auto_atendimentoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return banco.auto_atendimentoHelper.type ();
  }

}
