package banco;


/**
* banco/auto_atendimentoPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banco.idl
* Quarta-feira, 25 de Março de 2009 21h10min03s BRT
*/

public abstract class auto_atendimentoPOA extends org.omg.PortableServer.Servant
 implements banco.auto_atendimentoOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_boas_vindas", new java.lang.Integer (0));
    _methods.put ("saldo", new java.lang.Integer (1));
    _methods.put ("extrato", new java.lang.Integer (2));
    _methods.put ("tranferencia", new java.lang.Integer (3));
    _methods.put ("investimento", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // banco/auto_atendimento/_get_boas_vindas
       {
         String $result = null;
         $result = this.boas_vindas ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // banco/auto_atendimento/saldo
       {
         try {
           int c = banco.contaHelper.read (in);
           double $result = (double)0;
           $result = this.saldo (c);
           out = $rh.createReply();
           out.write_double ($result);
         } catch (banco.conta_inval $ex) {
           out = $rh.createExceptionReply ();
           banco.conta_invalHelper.write (out, $ex);
         }
         break;
       }

       case 2:  // banco/auto_atendimento/extrato
       {
         try {
           int c = banco.contaHelper.read (in);
           banco.transacoesHolder t = new banco.transacoesHolder ();
           org.omg.CORBA.DoubleHolder saldo = new org.omg.CORBA.DoubleHolder ();
           this.extrato (c, t, saldo);
           out = $rh.createReply();
           banco.transacoesHelper.write (out, t.value);
           banco.valorHelper.write (out, saldo.value);
         } catch (banco.conta_inval $ex) {
           out = $rh.createExceptionReply ();
           banco.conta_invalHelper.write (out, $ex);
         }
         break;
       }

       case 3:  // banco/auto_atendimento/tranferencia
       {
         try {
           int origem = banco.contaHelper.read (in);
           int destino = banco.contaHelper.read (in);
           double v = banco.valorHelper.read (in);
           this.tranferencia (origem, destino, v);
           out = $rh.createReply();
         } catch (banco.conta_inval $ex) {
           out = $rh.createExceptionReply ();
           banco.conta_invalHelper.write (out, $ex);
         } catch (banco.saldo_insuf $ex) {
           out = $rh.createExceptionReply ();
           banco.saldo_insufHelper.write (out, $ex);
         }
         break;
       }

       case 4:  // banco/auto_atendimento/investimento
       {
         try {
           int c = banco.contaHelper.read (in);
           banco.aplicacao apl = banco.aplicacaoHelper.read (in);
           double v = banco.valorHelper.read (in);
           this.investimento (c, apl, v);
           out = $rh.createReply();
         } catch (banco.conta_inval $ex) {
           out = $rh.createExceptionReply ();
           banco.conta_invalHelper.write (out, $ex);
         } catch (banco.saldo_insuf $ex) {
           out = $rh.createExceptionReply ();
           banco.saldo_insufHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:banco/auto_atendimento:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public auto_atendimento _this() 
  {
    return auto_atendimentoHelper.narrow(
    super._this_object());
  }

  public auto_atendimento _this(org.omg.CORBA.ORB orb) 
  {
    return auto_atendimentoHelper.narrow(
    super._this_object(orb));
  }


} // class auto_atendimentoPOA
