package banco;


/**
* banco/auto_atendimentoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banco.idl
* Quarta-feira, 25 de Março de 2009 21h10min03s BRT
*/

public interface auto_atendimentoOperations 
{
  String boas_vindas ();
  double saldo (int c) throws banco.conta_inval;
  void extrato (int c, banco.transacoesHolder t, org.omg.CORBA.DoubleHolder saldo) throws banco.conta_inval;
  void tranferencia (int origem, int destino, double v) throws banco.conta_inval, banco.saldo_insuf;
  void investimento (int c, banco.aplicacao apl, double v) throws banco.conta_inval, banco.saldo_insuf;
} // interface auto_atendimentoOperations
