package banco;


/**
* banco/caixa_eletronico.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banco.idl
* Quarta-feira, 25 de Março de 2009 21h10min03s BRT
*/

public interface caixa_eletronico extends caixa_eletronicoOperations, banco.auto_atendimento, org.omg.CORBA.portable.IDLEntity 
{
} // interface caixa_eletronico
