package banco;


/**
* banco/caixa_eletronicoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banco.idl
* Quarta-feira, 25 de Março de 2009 21h10min03s BRT
*/

public interface caixa_eletronicoOperations  extends banco.auto_atendimentoOperations
{
  void saque (int c, double v) throws banco.conta_inval, banco.saldo_insuf;
} // interface caixa_eletronicoOperations
