package banco;

/**
* banco/conta_invalHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banco.idl
* Quarta-feira, 25 de Março de 2009 21h10min03s BRT
*/

public final class conta_invalHolder implements org.omg.CORBA.portable.Streamable
{
  public banco.conta_inval value = null;

  public conta_invalHolder ()
  {
  }

  public conta_invalHolder (banco.conta_inval initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = banco.conta_invalHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    banco.conta_invalHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return banco.conta_invalHelper.type ();
  }

}
