package banco;


/**
* banco/conta_inval.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banco.idl
* Quarta-feira, 25 de Março de 2009 21h10min03s BRT
*/

public final class conta_inval extends org.omg.CORBA.UserException
{
  public int c = (int)0;

  public conta_inval ()
  {
    super(conta_invalHelper.id());
  } // ctor

  public conta_inval (int _c)
  {
    super(conta_invalHelper.id());
    c = _c;
  } // ctor


  public conta_inval (String $reason, int _c)
  {
    super(conta_invalHelper.id() + "  " + $reason);
    c = _c;
  } // ctor

} // class conta_inval
