package banco;


/**
* banco/moeda.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banco.idl
* Quarta-feira, 25 de Março de 2009 21h10min03s BRT
*/

public interface moeda
{
  public static final String value = "R$";
}
