package banco;


/**
* banco/nome_banco.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banco.idl
* Quarta-feira, 25 de Março de 2009 21h10min03s BRT
*/

public interface nome_banco
{
  public static final String value = "UFSC";
}
