package banco;

/**
* banco/saldo_insufHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banco.idl
* Quarta-feira, 25 de Março de 2009 21h10min03s BRT
*/

public final class saldo_insufHolder implements org.omg.CORBA.portable.Streamable
{
  public banco.saldo_insuf value = null;

  public saldo_insufHolder ()
  {
  }

  public saldo_insufHolder (banco.saldo_insuf initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = banco.saldo_insufHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    banco.saldo_insufHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return banco.saldo_insufHelper.type ();
  }

}
