package banco;


/**
* banco/saldo_insuf.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banco.idl
* Quarta-feira, 25 de Março de 2009 21h10min03s BRT
*/

public final class saldo_insuf extends org.omg.CORBA.UserException
{
  public double saldo = (double)0;

  public saldo_insuf ()
  {
    super(saldo_insufHelper.id());
  } // ctor

  public saldo_insuf (double _saldo)
  {
    super(saldo_insufHelper.id());
    saldo = _saldo;
  } // ctor


  public saldo_insuf (String $reason, double _saldo)
  {
    super(saldo_insufHelper.id() + "  " + $reason);
    saldo = _saldo;
  } // ctor

} // class saldo_insuf
