package banco;

/**
* banco/transacaoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banco.idl
* Quarta-feira, 25 de Março de 2009 21h10min03s BRT
*/

public final class transacaoHolder implements org.omg.CORBA.portable.Streamable
{
  public banco.transacao value = null;

  public transacaoHolder ()
  {
  }

  public transacaoHolder (banco.transacao initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = banco.transacaoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    banco.transacaoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return banco.transacaoHelper.type ();
  }

}
