package banco;


/**
* banco/transacao.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banco.idl
* Quarta-feira, 25 de Março de 2009 21h10min03s BRT
*/

public final class transacao implements org.omg.CORBA.portable.IDLEntity
{
  public int data = (int)0;

  // Formato: ddmmyyyy
  public String descricao = null;
  public double quantia = (double)0;

  public transacao ()
  {
  } // ctor

  public transacao (int _data, String _descricao, double _quantia)
  {
    data = _data;
    descricao = _descricao;
    quantia = _quantia;
  } // ctor

} // class transacao
