package banco;


/**
* banco/transacoesHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banco.idl
* Quarta-feira, 25 de Março de 2009 21h10min03s BRT
*/

abstract public class transacoesHelper
{
  private static String  _id = "IDL:banco/transacoes:1.0";

  public static void insert (org.omg.CORBA.Any a, banco.transacao[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static banco.transacao[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = banco.transacaoHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (banco.transacoesHelper.id (), "transacoes", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static banco.transacao[] read (org.omg.CORBA.portable.InputStream istream)
  {
    banco.transacao value[] = null;
    int _len0 = istream.read_long ();
    value = new banco.transacao[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = banco.transacaoHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, banco.transacao[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      banco.transacaoHelper.write (ostream, value[_i0]);
  }

}
