
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import org.omg.CORBA.MARSHAL;
import org.omg.CORBA.ORB;
import org.omg.CORBA.Object;
import org.omg.CORBA.ObjectHelper;
import org.omg.CORBA.StringHolder;
import org.omg.CORBA.portable.ApplicationException;
import org.omg.CORBA.portable.Delegate;
import org.omg.CORBA.portable.InputStream;
import org.omg.CORBA.portable.ObjectImpl;
import org.omg.CORBA.portable.OutputStream;
import org.omg.CORBA.portable.RemarshalException;

/**
 * _ServicoEventosStub.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from ServicoEventos.idl
 * Ter�a-feira, 31 de Mar�o de 2009 19h59min33s BRT
 */
public class _ServicoEventosStub extends ObjectImpl implements ServicoEventos {

    public boolean MeRegistre(Object ref, String evento) {
        InputStream $in = null;
        try {
            OutputStream $out = _request("MeRegistre", true);
            ObjectHelper.write($out, ref);
            $out.write_string(evento);
            $in = _invoke($out);
            boolean $result = $in.read_boolean();
            return $result;
        } catch (ApplicationException $ex) {
            $in = $ex.getInputStream();
            String _id = $ex.getId();
            throw new MARSHAL(_id);
        } catch (RemarshalException $rm) {
            return MeRegistre(ref, evento);
        } finally {
            _releaseReply($in);
        }
    } // MeRegistre

    public void ObterListaEventos(ServicoEventosPackage.listaEventosHolder lista) {
        InputStream $in = null;
        try {
            OutputStream $out = _request("ObterListaEventos", true);
            $in = _invoke($out);
            lista.value = ServicoEventosPackage.listaEventosHelper.read($in);
            return;
        } catch (ApplicationException $ex) {
            $in = $ex.getInputStream();
            String _id = $ex.getId();
            throw new MARSHAL(_id);
        } catch (RemarshalException $rm) {
            ObterListaEventos(lista);
        } finally {
            _releaseReply($in);
        }
    } // ObterListaEventos

    public boolean NovoEvento(String evento) {
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            OutputStream $out = _request("NovoEvento", true);
            $out.write_string(evento);
            $in = _invoke($out);
            boolean $result = $in.read_boolean();
            return $result;
        } catch (ApplicationException $ex) {
            $in = $ex.getInputStream();
            String _id = $ex.getId();
            throw new MARSHAL(_id);
        } catch (RemarshalException $rm) {
            return NovoEvento(evento);
        } finally {
            _releaseReply($in);
        }
    } // NovoEvento

    public boolean CadastrarEvento(String evento) {
        InputStream $in = null;
        try {
            OutputStream $out = _request("CadastrarEvento", true);
            $out.write_string(evento);
            $in = _invoke($out);
            boolean $result = $in.read_boolean();
            return $result;
        } catch (ApplicationException $ex) {
            $in = $ex.getInputStream();
            String _id = $ex.getId();
            throw new MARSHAL(_id);
        } catch (RemarshalException $rm) {
            return CadastrarEvento(evento);
        } finally {
            _releaseReply($in);
        }
    } // CadastrarEvento

    public boolean obterEventoQualquer(StringHolder evento) {
        InputStream $in = null;
        try {
            OutputStream $out = _request("obterEventoQualquer", true);
            $in = _invoke($out);
            boolean $result = $in.read_boolean();
            evento.value = $in.read_string();
            return $result;
        } catch (ApplicationException $ex) {
            $in = $ex.getInputStream();
            String _id = $ex.getId();
            throw new MARSHAL(_id);
        } catch (RemarshalException $rm) {
            return obterEventoQualquer(evento);
        } finally {
            _releaseReply($in);
        }
    } // obterEventoQualquer
    // Type-specific CORBA::Object operations
    private static String[] __ids = {
        "IDL:ServicoEventos:1.0"};

    public String[] _ids() {
        return (String[]) __ids.clone();
    }

    private void readObject(ObjectInputStream s) throws IOException {
        String str = s.readUTF();
        String[] args = null;
        java.util.Properties props = null;
        Object obj = ORB.init(args, props).string_to_object(str);
        Delegate delegate = ((ObjectImpl) obj)._get_delegate();
        _set_delegate(delegate);
    }

    private void writeObject(ObjectOutputStream s) throws IOException {
        String[] args = null;
        java.util.Properties props = null;
        String str = ORB.init(args, props).object_to_string(this);
        s.writeUTF(str);
    }
} // class _ServicoEventosStub
