
/**
* ClienteEventos.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClienteEventos.idl
* Terça-feira, 31 de Março de 2009 20h11min01s BRT
*/

public interface ClienteEventos extends ClienteEventosOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ClienteEventos
