
import org.omg.CORBA.Object;
import org.omg.CORBA.portable.IDLEntity;


/**
* ServicoEventos.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServicoEventos.idl
* Terça-feira, 31 de Março de 2009 19h59min33s BRT
*/

public interface ServicoEventos extends ServicoEventosOperations, Object, IDLEntity 
{
} // interface ServicoEventos
