interface ServicoEventos {
   typedef sequence<string> listaEventos; 
   boolean MeRegistre(in Object ref, in string evento);
   void ObterListaEventos(out listaEventos lista);
   boolean NovoEvento(in string evento);
   boolean CadastrarEvento(in string evento);
   boolean obterEventoQualquer(out string evento);
};
