
/**
* ServicoEventosHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServicoEventos.idl
* Terça-feira, 31 de Março de 2009 19h59min33s BRT
*/

public final class ServicoEventosHolder implements org.omg.CORBA.portable.Streamable
{
  public ServicoEventos value = null;

  public ServicoEventosHolder ()
  {
  }

  public ServicoEventosHolder (ServicoEventos initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServicoEventosHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServicoEventosHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServicoEventosHelper.type ();
  }

}
